import {
  Users,
  UserCheck,
  Palette,
  CalendarDays,
  Contact,
  Inbox,
  Library,
  MessageSquare,
  Lightbulb,
  DollarSign,
  CheckSquare,
  ListMusic,
  Send,
  Package,
} from "lucide-react";

export const WORKSPACE_TOOLS = [
  // Existing tools ...
  {
    id: "sections",
    title: "Band Sections",
    href: "/admin/sections",
    icon: Users,
    requiredRoles: ["admin", "section_leader"],
  },
  {
    id: "roster",
    title: "Band Roster & Invites",
    href: "/admin/roster",
    icon: UserCheck,
    requiredRoles: ["admin", "section_leader"],
  },
  {
    id: "attendance",
    title: "Section Attendance",
    href: "/admin/attendance",
    icon: CheckSquare,
    requiredRoles: ["admin", "gig_manager", "section_leader"],
  },
  {
    id: "inventory",
    title: "Equipment & Assets",
    href: "/admin/inventory",
    icon: Package,
    requiredRoles: ["admin", "gig_manager", "section_leader"],
  },
  {
    id: "gigs",
    title: "Gig Management Studio",
    href: "/admin/gigs",
    icon: CalendarDays,
    requiredRoles: ["admin", "gig_manager"],
  },
  {
    id: "setlists",
    title: "Setlist Studio",
    href: "/admin/setlists",
    icon: ListMusic,
    requiredRoles: ["admin", "gig_manager", "catalog_manager"],
  },
  {
    id: "dispatch",
    title: "Call Sheet Dispatch",
    href: "/admin/dispatch",
    icon: Send,
    requiredRoles: ["admin", "gig_manager"],
  },
  {
    id: "ledger",
    title: "Financial Ledger",
    href: "/admin/ledger",
    icon: DollarSign,
    requiredRoles: ["admin", "gig_manager"],
  },
  {
    id: "contacts",
    title: "Client CRM & Contacts",
    href: "/admin/contacts",
    icon: Contact,
    requiredRoles: ["admin", "gig_manager"],
  },
  {
    id: "leads",
    title: "Booking Leads",
    href: "/admin/inquiries",
    icon: Inbox,
    requiredRoles: ["admin", "gig_manager"],
  },
  {
    id: "catalog",
    title: "Catalog Studio",
    href: "/admin/catalog",
    icon: Library,
    requiredRoles: ["admin", "catalog_manager"],
  },
  {
    id: "suggestions",
    title: "Suggestion Triage",
    href: "/admin/suggestions",
    icon: Lightbulb,
    requiredRoles: ["admin", "catalog_manager"],
  },
  {
    id: "theme",
    title: "Brand & Palette",
    href: "/admin/theme",
    icon: Palette,
    requiredRoles: ["admin"],
  },
  {
    id: "comments",
    title: "Comment Moderation",
    href: "/admin/comments",
    icon: MessageSquare,
    requiredRoles: ["admin"],
  },
];
