import { z } from "zod";

export const ResourceTypeEnum = z.enum(["image", "document", "audio", "video", "other"]);
export type ResourceType = z.infer<typeof ResourceTypeEnum>;

export const ResourceCategoryEnum = z.enum([
  "hero",
  "header",
  "logo",
  "gallery",
  "flyer",
  "document",
  "press_kit",
  "general",
]);
export type ResourceCategory = z.infer<typeof ResourceCategoryEnum>;

export const ResourceAssetSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1, "Resource name is required"),
  url: z.string().url("Must be a valid URL"),
  type: ResourceTypeEnum.default("image"),
  category: ResourceCategoryEnum.default("general"),
  description: z.string().default(""),
  altText: z.string().default(""),
  tags: z.array(z.string()).default([]),
  dimensions: z
    .object({
      width: z.number().optional(),
      height: z.number().optional(),
    })
    .optional(),
  fileSize: z.string().default(""),
  mimeType: z.string().default(""),
  thumbnailUrl: z.string().default(""),
  uploadedBy: z.string().default(""),
  isPublic: z.boolean().default(true),
  createdAt: z.string().default(() => new Date().toISOString()),
  updatedAt: z.string().default(() => new Date().toISOString()),
});

export type ResourceAsset = z.infer<typeof ResourceAssetSchema>;

export const ResourceAssetInputSchema = ResourceAssetSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type ResourceAssetInput = z.infer<typeof ResourceAssetInputSchema>;

export const DEFAULT_RESOURCES: ResourceAsset[] = [
  {
    id: "res_parade_revelry",
    name: "Parade Street Revelry",
    url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1600&q=80",
    type: "image",
    category: "header",
    description: "Greenfield Holiday Parade route with crowds cheering marching brass.",
    altText: "Eagleburger Band marching parade revelry with crowd",
    tags: ["parade", "street", "crowd", "header", "hero"],
    fileSize: "1.4 MB",
    mimeType: "image/jpeg",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=400&q=80",
    uploadedBy: "system",
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "res_night_festival",
    name: "Night Festival Stage",
    url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1600&q=80",
    type: "image",
    category: "hero",
    description: "Vibrant festival stage under dramatic concert lighting and roaring applause.",
    altText: "Eagleburger Band night festival stage performance",
    tags: ["festival", "stage", "lights", "night", "hero"],
    fileSize: "1.8 MB",
    mimeType: "image/jpeg",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=400&q=80",
    uploadedBy: "system",
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "res_brass_battery",
    name: "Brass Battery & Horns",
    url: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1600&q=80",
    type: "image",
    category: "header",
    description: "Polished brass instruments, glistening bells, and drum battery ready for downbeat.",
    altText: "Eagleburger Band brass instruments and horn line in sunshine",
    tags: ["brass", "horns", "percussion", "header", "instruments"],
    fileSize: "1.2 MB",
    mimeType: "image/jpeg",
    thumbnailUrl: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=400&q=80",
    uploadedBy: "system",
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "res_acoustic_celebration",
    name: "Acoustic Street Celebration",
    url: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1600&q=80",
    type: "image",
    category: "gallery",
    description: "Neighborhood block party and street dancing surrounding mobile musicians.",
    altText: "Eagleburger Band acoustic street celebration and dancing crowd",
    tags: ["block_party", "celebration", "community", "street", "gallery"],
    fileSize: "1.6 MB",
    mimeType: "image/jpeg",
    thumbnailUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=400&q=80",
    uploadedBy: "system",
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "res_drumline_groove",
    name: "Drumline Cadence Groove",
    url: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=1600&q=80",
    type: "image",
    category: "hero",
    description: "High-octane snare and bass drums keeping the pulse of Pittsburgh.",
    altText: "Marching snare drum and percussion battery line in motion",
    tags: ["drums", "percussion", "cadence", "rhythm", "hero"],
    fileSize: "1.5 MB",
    mimeType: "image/jpeg",
    thumbnailUrl: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=400&q=80",
    uploadedBy: "system",
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "res_press_kit_pdf",
    name: "Eagleburger Band Official Press Kit (EPK 2026)",
    url: "https://raw.githubusercontent.com/eagleburgerband/assets/main/docs/Eagleburger_Band_EPK_2026.pdf",
    type: "document",
    category: "press_kit",
    description: "Full electronic press kit including biography, hi-res logos, performance history, and press quotes.",
    altText: "Eagleburger Band Electronic Press Kit Document PDF",
    tags: ["epk", "press", "bio", "booking", "document"],
    fileSize: "4.8 MB",
    mimeType: "application/pdf",
    thumbnailUrl: "",
    uploadedBy: "system",
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "res_tech_rider_pdf",
    name: "Acoustic Logistics & Tech Rider",
    url: "https://raw.githubusercontent.com/eagleburgerband/assets/main/docs/Eagleburger_Tech_Rider.pdf",
    type: "document",
    category: "document",
    description: "Event coordinator logistics sheet detailing staging area, mobile staging footprint, water breaks, and warmup zones.",
    altText: "Logistics and acoustic technical rider PDF",
    tags: ["logistics", "rider", "coordinators", "planner", "document"],
    fileSize: "1.1 MB",
    mimeType: "application/pdf",
    thumbnailUrl: "",
    uploadedBy: "system",
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "res_band_logo_crest",
    name: "Eagleburger Crest Emblem (Gold on Dark)",
    url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    type: "image",
    category: "logo",
    description: "Official heraldic crest emblem for print, banners, and header marks.",
    altText: "Eagleburger Band gold crest emblem logo",
    tags: ["logo", "brand", "crest", "vector", "mark"],
    fileSize: "820 KB",
    mimeType: "image/png",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80",
    uploadedBy: "system",
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

