name: Deploy Master to eagleburgerband.com

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v3

      - name: Install and Build
        run: |
          npm install
          npm run build
          echo "eagleburgerband.com" > ./build/CNAME

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - uses: actions/deploy-pages@v4
